version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: main.Dockerfile
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  angular:
    container_name: angular
    image: production-image
    build:
      context: ./angular
      dockerfile: angular.Dockerfile
    command: sh -c "cd angular && npm run start:docker"
    ports:
      - "4200:4200"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  pgdata:
  node_modules: